### ISSUE TITLE
WikiのESP32マイコンデバイスのポート指定について

### ISSUE THREAD

**Issue by matsudai** [gfd-dennou-club/mrubyc-esp32#24]
環境構築方法など詳細にご記載くださり、大変助かっております。

[Wikiの 基本 > はじめの一歩 (プログラムの作成と書き込み) > 3. 準備 > ESP32 マイコンのデバイス名の確認](https://github.com/gfd-dennou-club/mrubyc-esp32/wiki/Users_%E3%83%97%E3%83%AD%E3%82%B0%E3%83%A9%E3%83%A0%E3%81%AE%E4%BD%9C%E6%88%90%E3%81%A8%E6%9B%B8%E3%81%8D%E8%BE%BC%E3%81%BF#esp32-%E3%83%9E%E3%82%A4%E3%82%B3%E3%83%B3%E3%81%AE%E3%83%87%E3%83%90%E3%82%A4%E3%82%B9%E5%90%8D%E3%81%AE%E7%A2%BA%E8%AA%8D) にて、下記の記述があります。

> もし，デバイス名が /dev/ttyUSB0 以外だった場合には，環境変数 ESP32PORT を設定すること (もしくは，Makefile の "port0 = " の行を適切に修正すること)．
> ```
> $ export ESP32PORT=/dev/ttyUSB1
> ```

この環境変数名 `ESP32PORT` ではポートが変更されないようでした。

[Makefile](https://github.com/gfd-dennou-club/mrubyc-esp32/blob/master/Makefile#L9) では `PORT` が参照されるため、この環境変数 `PORT` に読み替えたところ正常に動作しました。

`ESP32PORT` または `PORT` のどちらかを修正いただけますと幸いです。

**Comment by sugiymki** [comment]
ご指摘ありがとうございます．現状に合わせて wiki を修正しました．
また何かお気づきのことがあれば，ご連絡頂けると喜びます．

**Comment by matsudai** [comment]
@sugiymki お忙しい中ご対応いただきありがとうございます！
