### ISSUE TITLE
ESP32-PICOへのSPIFFS書き込みの失敗

### ISSUE THREAD

**Issue by matsudai** [gfd-dennou-club/mrubyc-esp32#27]
* 開発環境
    * WSL1 (Debian 11)
    * ruby 2.7.0
    * mruby 2.1.0
    * mruby/c -> [2022-08-06時点のmrubyc-esp32/master](https://github.com/gfd-dennou-club/mrubyc-esp32/tree/d87c826440c3a819e68d5a43de5556a0e348feba)
    * Python 3.9.2
    * ESP-IDF v4.2.3
* 実行環境
    * (M5Stackシリーズ) ATOM Lite (ESP32-PICO-D4 (revision 1))

[make spiffsで書き込むときのbaudが921600で固定](https://github.com/gfd-dennou-club/mrubyc-esp32/blob/d87c826440c3a819e68d5a43de5556a0e348feba/Makefile#L54) されております。

手元のESP32-PICOでは、このレートでの書き込みに失敗しました。  
また、921600の代わりに115200を指定すると成功することを確認しました。

環境変数 `PORT` の指定に倣い、環境変数 `BAUD` で変更できるようPRしますので、
お時間があるときにご確認いただければ幸いです。

**Comment by sugiymki** [comment]
なるほど，そうだったのですね．ESP32-PICO に書き込みできないことは把握していたのですが，その対処方法は全然わかっていませんでした．大変助かりました．今，手元に ATOM Lite が無いので，お盆明けに試してみます．
