### ISSUE TITLE
(Wiki) VMのコンパイル設定を行うmake menuconfigコマンドの変更によるエラー発生

### ISSUE THREAD

**Issue by matsudai** [gfd-dennou-club/mrubyc-esp32#36]
* 開発環境
    * WSL1 (Debian 12)
    * ruby 3.1.2
    * mruby 3.3.0
    * mruby/c -> [2024-10-06時点のmrubyc-esp32/master](https://github.com/gfd-dennou-club/mrubyc-esp32/tree/c1b3a7d72ddeb2008300c99bb0f81cb13600d028)
    * Python 3.11.2
    * ESP-IDF v5.2.3
* 実行環境
    * M5Stack BASIC (ESP32-D0WDQ6-V3)

[Wikiの「VM のコンパイルとマイコンへの書き出し」](https://github.com/gfd-dennou-club/mrubyc-esp32/wiki/Developers_%E3%83%97%E3%83%AD%E3%82%B0%E3%83%A9%E3%83%A0%E4%BD%9C%E6%88%90%E3%83%BBVM%E3%82%B3%E3%83%B3%E3%83%91%E3%82%A4%E3%83%AB%E3%83%BB%E6%9B%B8%E3%81%8D%E8%BE%BC%E3%81%BF#vm-%E3%81%AE%E3%82%B3%E3%83%B3%E3%83%91%E3%82%A4%E3%83%AB%E3%81%A8%E3%83%9E%E3%82%A4%E3%82%B3%E3%83%B3%E3%81%B8%E3%81%AE%E6%9B%B8%E3%81%8D%E5%87%BA%E3%81%97) で使用される `make menuconfig` コマンドが、ESP-IDF 3→4系で変更されておりました。

* v3.3のREADME : [`make menuconfig`](https://github.com/espressif/esp-idf/tree/release/v3.3#configuring-the-project)
* v4.0のREADME : [`idf.py menuconfig`](https://github.com/espressif/esp-idf/tree/release/v4.0#configuring-the-project)

お手数ですが、ご確認いただけますと幸いです。

```txt
$ make menuconfig

make: *** No rule to make target 'menuconfig'.  Stop.
```

**Comment by sugiymki** [comment]
確認しました．Makefile ファイルに追記し，make menuconfig が動くようにしました．

**Comment by matsudai** [comment]
@sugiymki ご対応いただきありがとうございます。
